using System;
using System.IO;
using System.Reflection;
using Microsoft.EntityFrameworkCore;            // ← this one
using Microsoft.OpenApi.Models;
using RestApiExample.Data;
using RestApiExample.Repositories;
using RestApiExample.Services;
using AutoMapper;
using RestApiExample.Mapping;

var builder = WebApplication.CreateBuilder(args);

// 1. Configure Services
builder.Services.AddCors(options =>
{
    options.AddPolicy("ReactDevPolicy", policy =>
        policy
          .WithOrigins("http://localhost:3000")
          .AllowAnyHeader()
          .AllowAnyMethod()
    );
});

builder.Services.AddControllers();

builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseInMemoryDatabase("H2InMemory"));

builder.Services.AddScoped<IProductRepository, ProductRepository>();
builder.Services.AddScoped<IProductService, ProductService>();

// AutoMapper profiles
builder.Services.AddAutoMapper(typeof(MappingProfile));
builder.Services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Agricura Product API", Version = "v1",
        Description = "API for managing products in Agricura Farmtech system." });

    // Locate the XML file being generated by ASP.NET...
    var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    c.IncludeXmlComments(xmlPath);
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "Product API V1");
        c.RoutePrefix = string.Empty;
    });
}

// ... rest of middleware ...
app.MapControllers();
app.Run();